app:
  env: local
  addr: 127.0.0.1
  port: 8080
  app_name: lbemi-app
  app_url: http://localhost
log:
  level: info
  root_dir: .
  is_file: false
  file_name: app.log
  format:
  show_line: true
  max_backup: 500
  max_age: 10
  compress: true
