"use strict";
var _a, _b, _c, _d;
Object.defineProperty(exports, "__esModule", { value: true });
exports.resolve = exports.NumberStringUnionResolver = exports.ImplicitTokenResolver = exports.LazyResolver = exports.ResolutionContext = void 0;
const JSII_RTTI_SYMBOL_1 = Symbol.for("jsii.rtti");
const app_1 = require("./app");
const lazy_1 = require("./lazy");
/**
 * Context object for a specific resolution process.
 */
class ResolutionContext {
    constructor(
    /**
     * Which ApiObject is currently being resolved.
     */
    obj, 
    /**
     * Which key is currently being resolved.
     */
    key, 
    /**
     * The value associated to the key currently being resolved.
     */
    value) {
        this.obj = obj;
        this.key = key;
        this.value = value;
        /**
         * Whether or not the value was replaced by invoking the `replaceValue` method.
         */
        this.replaced = false;
    }
    /**
     * Replaces the original value in this resolution context
     * with a new value. The new value is what will end up in the manifest.
     */
    replaceValue(newValue) {
        this.replacedValue = newValue;
        this.replaced = true;
    }
}
exports.ResolutionContext = ResolutionContext;
_a = JSII_RTTI_SYMBOL_1;
ResolutionContext[_a] = { fqn: "cdk8s.ResolutionContext", version: "2.68.60" };
/**
 * Resolvers instanecs of `Lazy`.
 */
class LazyResolver {
    resolve(context) {
        if (context.value instanceof lazy_1.Lazy) {
            const resolved = context.value.produce();
            context.replaceValue(resolved);
        }
    }
}
exports.LazyResolver = LazyResolver;
_b = JSII_RTTI_SYMBOL_1;
LazyResolver[_b] = { fqn: "cdk8s.LazyResolver", version: "2.68.60" };
/**
 * Resolves implicit tokens.
 */
class ImplicitTokenResolver {
    resolve(context) {
        if (typeof (context.value.resolve) === 'function') {
            const resolved = context.value.resolve();
            context.replaceValue(resolved);
        }
    }
}
exports.ImplicitTokenResolver = ImplicitTokenResolver;
_c = JSII_RTTI_SYMBOL_1;
ImplicitTokenResolver[_c] = { fqn: "cdk8s.ImplicitTokenResolver", version: "2.68.60" };
/**
 * Resolves union types that allow using either number or string (as generated by the CLI).
 *
 * E.g IntOrString, Quantity, ...
 */
class NumberStringUnionResolver {
    resolve(context) {
        if (context.value.constructor === Object) {
            // we only want to resolve union classes, not plain dictionaries
            return;
        }
        if (NumberStringUnionResolver.TYPES.includes(typeof (context.value.value))) {
            // replace with a dictionary because the L1 proceeds to access the .value
            // property after resolution.
            context.replaceValue({ value: context.value.value });
        }
    }
}
exports.NumberStringUnionResolver = NumberStringUnionResolver;
_d = JSII_RTTI_SYMBOL_1;
NumberStringUnionResolver[_d] = { fqn: "cdk8s.NumberStringUnionResolver", version: "2.68.60" };
NumberStringUnionResolver.TYPES = ['number', 'string'];
/**
 * Resolves any value attached to a specific ApiObject.
 */
function resolve(key, value, apiObject) {
    const resolvers = app_1.App.of(apiObject).resolvers;
    if (value == null) {
        return value;
    }
    // give dibs to the resolvers as they are more specific
    const context = new ResolutionContext(apiObject, key, value);
    for (const resolver of resolvers) {
        resolver.resolve(context);
        if (context.replaced) {
            // stop when the first resolver replaces the value.
            return resolve(key, context.replacedValue, apiObject);
        }
    }
    // array - resolve each element
    if (Array.isArray(value)) {
        return value.map((x, i) => resolve([...key, `${i}`], x, apiObject));
    }
    // dictionrary - resolve leafs
    if (value.constructor == Object) {
        const result = {};
        for (const [k, v] of Object.entries(value)) {
            result[k] = resolve([...key, k], v, apiObject);
        }
        return result;
    }
    return value;
}
exports.resolve = resolve;
//# sourceMappingURL=data:application/json;base64,eyJ2ZXJzaW9uIjozLCJmaWxlIjoicmVzb2x2ZS5qcyIsInNvdXJjZVJvb3QiOiIiLCJzb3VyY2VzIjpbIi4uL3NyYy9yZXNvbHZlLnRzIl0sIm5hbWVzIjpbXSwibWFwcGluZ3MiOiI7Ozs7O0FBQ0EsK0JBQTRCO0FBQzVCLGlDQUE4QjtBQUU5Qjs7R0FFRztBQUNILE1BQWEsaUJBQWlCO0lBWTVCO0lBQ0U7O09BRUc7SUFDYSxHQUFjO0lBQzlCOztPQUVHO0lBQ2EsR0FBYTtJQUM3Qjs7T0FFRztJQUNhLEtBQVU7UUFSVixRQUFHLEdBQUgsR0FBRyxDQUFXO1FBSWQsUUFBRyxHQUFILEdBQUcsQ0FBVTtRQUliLFVBQUssR0FBTCxLQUFLLENBQUs7UUFqQjVCOztXQUVHO1FBQ0ksYUFBUSxHQUFZLEtBQUssQ0FBQztJQWVqQyxDQUFDO0lBRUQ7OztPQUdHO0lBQ0ksWUFBWSxDQUFDLFFBQWE7UUFDL0IsSUFBSSxDQUFDLGFBQWEsR0FBRyxRQUFRLENBQUM7UUFDOUIsSUFBSSxDQUFDLFFBQVEsR0FBRyxJQUFJLENBQUM7SUFDdkIsQ0FBQzs7QUFsQ0gsOENBb0NDOzs7QUFjRDs7R0FFRztBQUNILE1BQWEsWUFBWTtJQUVoQixPQUFPLENBQUMsT0FBMEI7UUFDdkMsSUFBSSxPQUFPLENBQUMsS0FBSyxZQUFZLFdBQUksRUFBRSxDQUFDO1lBQ2xDLE1BQU0sUUFBUSxHQUFHLE9BQU8sQ0FBQyxLQUFLLENBQUMsT0FBTyxFQUFFLENBQUM7WUFDekMsT0FBTyxDQUFDLFlBQVksQ0FBQyxRQUFRLENBQUMsQ0FBQztRQUNqQyxDQUFDO0lBQ0gsQ0FBQzs7QUFQSCxvQ0FRQzs7O0FBRUQ7O0dBRUc7QUFDSCxNQUFhLHFCQUFxQjtJQUV6QixPQUFPLENBQUMsT0FBMEI7UUFFdkMsSUFBSSxPQUFPLENBQUMsT0FBTyxDQUFDLEtBQUssQ0FBQyxPQUFPLENBQUMsS0FBSyxVQUFVLEVBQUUsQ0FBQztZQUNsRCxNQUFNLFFBQVEsR0FBRyxPQUFPLENBQUMsS0FBSyxDQUFDLE9BQU8sRUFBRSxDQUFDO1lBQ3pDLE9BQU8sQ0FBQyxZQUFZLENBQUMsUUFBUSxDQUFDLENBQUM7UUFDakMsQ0FBQztJQUVILENBQUM7O0FBVEgsc0RBV0M7OztBQUVEOzs7O0dBSUc7QUFDSCxNQUFhLHlCQUF5QjtJQUk3QixPQUFPLENBQUMsT0FBMEI7UUFFdkMsSUFBSSxPQUFPLENBQUMsS0FBSyxDQUFDLFdBQVcsS0FBSyxNQUFNLEVBQUUsQ0FBQztZQUN6QyxnRUFBZ0U7WUFDaEUsT0FBTztRQUNULENBQUM7UUFFRCxJQUFJLHlCQUF5QixDQUFDLEtBQUssQ0FBQyxRQUFRLENBQUMsT0FBTSxDQUFDLE9BQU8sQ0FBQyxLQUFLLENBQUMsS0FBSyxDQUFDLENBQUMsRUFBRSxDQUFDO1lBQzFFLHlFQUF5RTtZQUN6RSw2QkFBNkI7WUFDN0IsT0FBTyxDQUFDLFlBQVksQ0FBQyxFQUFFLEtBQUssRUFBRSxPQUFPLENBQUMsS0FBSyxDQUFDLEtBQUssRUFBRSxDQUFDLENBQUM7UUFDdkQsQ0FBQztJQUVILENBQUM7O0FBakJILDhEQW1CQzs7O0FBakJ5QiwrQkFBSyxHQUFHLENBQUMsUUFBUSxFQUFFLFFBQVEsQ0FBQyxDQUFDO0FBbUJ2RDs7R0FFRztBQUNILFNBQWdCLE9BQU8sQ0FBQyxHQUFhLEVBQUUsS0FBVSxFQUFFLFNBQW9CO0lBRXJFLE1BQU0sU0FBUyxHQUFHLFNBQUcsQ0FBQyxFQUFFLENBQUMsU0FBUyxDQUFDLENBQUMsU0FBUyxDQUFDO0lBRTlDLElBQUksS0FBSyxJQUFJLElBQUksRUFBRSxDQUFDO1FBQ2xCLE9BQU8sS0FBSyxDQUFDO0lBQ2YsQ0FBQztJQUVELHVEQUF1RDtJQUN2RCxNQUFNLE9BQU8sR0FBRyxJQUFJLGlCQUFpQixDQUFDLFNBQVMsRUFBRSxHQUFHLEVBQUUsS0FBSyxDQUFDLENBQUM7SUFDN0QsS0FBSyxNQUFNLFFBQVEsSUFBSSxTQUFTLEVBQUUsQ0FBQztRQUNqQyxRQUFRLENBQUMsT0FBTyxDQUFDLE9BQU8sQ0FBQyxDQUFDO1FBQzFCLElBQUksT0FBTyxDQUFDLFFBQVEsRUFBRSxDQUFDO1lBQ3JCLG1EQUFtRDtZQUNuRCxPQUFPLE9BQU8sQ0FBQyxHQUFHLEVBQUUsT0FBTyxDQUFDLGFBQWEsRUFBRSxTQUFTLENBQUMsQ0FBQztRQUN4RCxDQUFDO0lBQ0gsQ0FBQztJQUVELCtCQUErQjtJQUMvQixJQUFJLEtBQUssQ0FBQyxPQUFPLENBQUMsS0FBSyxDQUFDLEVBQUUsQ0FBQztRQUN6QixPQUFPLEtBQUssQ0FBQyxHQUFHLENBQUMsQ0FBQyxDQUFDLEVBQUUsQ0FBQyxFQUFFLEVBQUUsQ0FBQyxPQUFPLENBQUMsQ0FBQyxHQUFHLEdBQUcsRUFBRSxHQUFHLENBQUMsRUFBRSxDQUFDLEVBQUUsQ0FBQyxFQUFFLFNBQVMsQ0FBQyxDQUFDLENBQUM7SUFDdEUsQ0FBQztJQUVELDhCQUE4QjtJQUM5QixJQUFJLEtBQUssQ0FBQyxXQUFXLElBQUksTUFBTSxFQUFFLENBQUM7UUFDaEMsTUFBTSxNQUFNLEdBQVEsRUFBRSxDQUFDO1FBQ3ZCLEtBQUssTUFBTSxDQUFDLENBQUMsRUFBRSxDQUFDLENBQUMsSUFBSSxNQUFNLENBQUMsT0FBTyxDQUFDLEtBQUssQ0FBQyxFQUFFLENBQUM7WUFDM0MsTUFBTSxDQUFDLENBQUMsQ0FBQyxHQUFHLE9BQU8sQ0FBQyxDQUFDLEdBQUcsR0FBRyxFQUFFLENBQUMsQ0FBQyxFQUFFLENBQUMsRUFBRSxTQUFTLENBQUMsQ0FBQztRQUNqRCxDQUFDO1FBQ0QsT0FBTyxNQUFNLENBQUM7SUFDaEIsQ0FBQztJQUVELE9BQU8sS0FBSyxDQUFDO0FBRWYsQ0FBQztBQWxDRCwwQkFrQ0MiLCJzb3VyY2VzQ29udGVudCI6WyJpbXBvcnQgeyBBcGlPYmplY3QgfSBmcm9tICcuL2FwaS1vYmplY3QnO1xuaW1wb3J0IHsgQXBwIH0gZnJvbSAnLi9hcHAnO1xuaW1wb3J0IHsgTGF6eSB9IGZyb20gJy4vbGF6eSc7XG5cbi8qKlxuICogQ29udGV4dCBvYmplY3QgZm9yIGEgc3BlY2lmaWMgcmVzb2x1dGlvbiBwcm9jZXNzLlxuICovXG5leHBvcnQgY2xhc3MgUmVzb2x1dGlvbkNvbnRleHQge1xuXG4gIC8qKlxuICAgKiBUaGUgcmVwbGFjZWQgdmFsdWUgdGhhdCB3YXMgc2V0IHZpYSB0aGUgYHJlcGxhY2VWYWx1ZWAgbWV0aG9kLlxuICAgKi9cbiAgcHVibGljIHJlcGxhY2VkVmFsdWU6IGFueTtcblxuICAvKipcbiAgICogV2hldGhlciBvciBub3QgdGhlIHZhbHVlIHdhcyByZXBsYWNlZCBieSBpbnZva2luZyB0aGUgYHJlcGxhY2VWYWx1ZWAgbWV0aG9kLlxuICAgKi9cbiAgcHVibGljIHJlcGxhY2VkOiBib29sZWFuID0gZmFsc2U7XG5cbiAgY29uc3RydWN0b3IoXG4gICAgLyoqXG4gICAgICogV2hpY2ggQXBpT2JqZWN0IGlzIGN1cnJlbnRseSBiZWluZyByZXNvbHZlZC5cbiAgICAgKi9cbiAgICBwdWJsaWMgcmVhZG9ubHkgb2JqOiBBcGlPYmplY3QsXG4gICAgLyoqXG4gICAgICogV2hpY2gga2V5IGlzIGN1cnJlbnRseSBiZWluZyByZXNvbHZlZC5cbiAgICAgKi9cbiAgICBwdWJsaWMgcmVhZG9ubHkga2V5OiBzdHJpbmdbXSxcbiAgICAvKipcbiAgICAgKiBUaGUgdmFsdWUgYXNzb2NpYXRlZCB0byB0aGUga2V5IGN1cnJlbnRseSBiZWluZyByZXNvbHZlZC5cbiAgICAgKi9cbiAgICBwdWJsaWMgcmVhZG9ubHkgdmFsdWU6IGFueSkge1xuICB9XG5cbiAgLyoqXG4gICAqIFJlcGxhY2VzIHRoZSBvcmlnaW5hbCB2YWx1ZSBpbiB0aGlzIHJlc29sdXRpb24gY29udGV4dFxuICAgKiB3aXRoIGEgbmV3IHZhbHVlLiBUaGUgbmV3IHZhbHVlIGlzIHdoYXQgd2lsbCBlbmQgdXAgaW4gdGhlIG1hbmlmZXN0LlxuICAgKi9cbiAgcHVibGljIHJlcGxhY2VWYWx1ZShuZXdWYWx1ZTogYW55KSB7XG4gICAgdGhpcy5yZXBsYWNlZFZhbHVlID0gbmV3VmFsdWU7XG4gICAgdGhpcy5yZXBsYWNlZCA9IHRydWU7XG4gIH1cblxufVxuXG4vKipcbiAqIENvbnRyYWN0IGZvciByZXNvbHZlciBvYmplY3RzLlxuICovXG5leHBvcnQgaW50ZXJmYWNlIElSZXNvbHZlciB7XG5cbiAgLyoqXG4gICAqIFRoaXMgZnVuY3Rpb24gaXMgaW52b2tlZCBvbiBldmVyeSBwcm9wZXJ0eSBkdXJpbmcgY2RrOHMgc3ludGhlc2lzLlxuICAgKiBUbyByZXBsYWNlIGEgdmFsdWUsIGltcGxlbWVudGF0aW9ucyBtdXN0IGludm9rZSBgY29udGV4dC5yZXBsYWNlVmFsdWVgLlxuICAgKi9cbiAgcmVzb2x2ZShjb250ZXh0OiBSZXNvbHV0aW9uQ29udGV4dCk6IHZvaWQ7XG59XG5cbi8qKlxuICogUmVzb2x2ZXJzIGluc3RhbmVjcyBvZiBgTGF6eWAuXG4gKi9cbmV4cG9ydCBjbGFzcyBMYXp5UmVzb2x2ZXIgaW1wbGVtZW50cyBJUmVzb2x2ZXIge1xuXG4gIHB1YmxpYyByZXNvbHZlKGNvbnRleHQ6IFJlc29sdXRpb25Db250ZXh0KTogdm9pZCB7XG4gICAgaWYgKGNvbnRleHQudmFsdWUgaW5zdGFuY2VvZiBMYXp5KSB7XG4gICAgICBjb25zdCByZXNvbHZlZCA9IGNvbnRleHQudmFsdWUucHJvZHVjZSgpO1xuICAgICAgY29udGV4dC5yZXBsYWNlVmFsdWUocmVzb2x2ZWQpO1xuICAgIH1cbiAgfVxufVxuXG4vKipcbiAqIFJlc29sdmVzIGltcGxpY2l0IHRva2Vucy5cbiAqL1xuZXhwb3J0IGNsYXNzIEltcGxpY2l0VG9rZW5SZXNvbHZlciBpbXBsZW1lbnRzIElSZXNvbHZlciB7XG5cbiAgcHVibGljIHJlc29sdmUoY29udGV4dDogUmVzb2x1dGlvbkNvbnRleHQpOiB2b2lkIHtcblxuICAgIGlmICh0eXBlb2YgKGNvbnRleHQudmFsdWUucmVzb2x2ZSkgPT09ICdmdW5jdGlvbicpIHtcbiAgICAgIGNvbnN0IHJlc29sdmVkID0gY29udGV4dC52YWx1ZS5yZXNvbHZlKCk7XG4gICAgICBjb250ZXh0LnJlcGxhY2VWYWx1ZShyZXNvbHZlZCk7XG4gICAgfVxuXG4gIH1cblxufVxuXG4vKipcbiAqIFJlc29sdmVzIHVuaW9uIHR5cGVzIHRoYXQgYWxsb3cgdXNpbmcgZWl0aGVyIG51bWJlciBvciBzdHJpbmcgKGFzIGdlbmVyYXRlZCBieSB0aGUgQ0xJKS5cbiAqXG4gKiBFLmcgSW50T3JTdHJpbmcsIFF1YW50aXR5LCAuLi5cbiAqL1xuZXhwb3J0IGNsYXNzIE51bWJlclN0cmluZ1VuaW9uUmVzb2x2ZXIgaW1wbGVtZW50cyBJUmVzb2x2ZXIge1xuXG4gIHByaXZhdGUgc3RhdGljIHJlYWRvbmx5IFRZUEVTID0gWydudW1iZXInLCAnc3RyaW5nJ107XG5cbiAgcHVibGljIHJlc29sdmUoY29udGV4dDogUmVzb2x1dGlvbkNvbnRleHQpOiB2b2lkIHtcblxuICAgIGlmIChjb250ZXh0LnZhbHVlLmNvbnN0cnVjdG9yID09PSBPYmplY3QpIHtcbiAgICAgIC8vIHdlIG9ubHkgd2FudCB0byByZXNvbHZlIHVuaW9uIGNsYXNzZXMsIG5vdCBwbGFpbiBkaWN0aW9uYXJpZXNcbiAgICAgIHJldHVybjtcbiAgICB9XG5cbiAgICBpZiAoTnVtYmVyU3RyaW5nVW5pb25SZXNvbHZlci5UWVBFUy5pbmNsdWRlcyh0eXBlb2YoY29udGV4dC52YWx1ZS52YWx1ZSkpKSB7XG4gICAgICAvLyByZXBsYWNlIHdpdGggYSBkaWN0aW9uYXJ5IGJlY2F1c2UgdGhlIEwxIHByb2NlZWRzIHRvIGFjY2VzcyB0aGUgLnZhbHVlXG4gICAgICAvLyBwcm9wZXJ0eSBhZnRlciByZXNvbHV0aW9uLlxuICAgICAgY29udGV4dC5yZXBsYWNlVmFsdWUoeyB2YWx1ZTogY29udGV4dC52YWx1ZS52YWx1ZSB9KTtcbiAgICB9XG5cbiAgfVxuXG59XG5cbi8qKlxuICogUmVzb2x2ZXMgYW55IHZhbHVlIGF0dGFjaGVkIHRvIGEgc3BlY2lmaWMgQXBpT2JqZWN0LlxuICovXG5leHBvcnQgZnVuY3Rpb24gcmVzb2x2ZShrZXk6IHN0cmluZ1tdLCB2YWx1ZTogYW55LCBhcGlPYmplY3Q6IEFwaU9iamVjdCk6IGFueSB7XG5cbiAgY29uc3QgcmVzb2x2ZXJzID0gQXBwLm9mKGFwaU9iamVjdCkucmVzb2x2ZXJzO1xuXG4gIGlmICh2YWx1ZSA9PSBudWxsKSB7XG4gICAgcmV0dXJuIHZhbHVlO1xuICB9XG5cbiAgLy8gZ2l2ZSBkaWJzIHRvIHRoZSByZXNvbHZlcnMgYXMgdGhleSBhcmUgbW9yZSBzcGVjaWZpY1xuICBjb25zdCBjb250ZXh0ID0gbmV3IFJlc29sdXRpb25Db250ZXh0KGFwaU9iamVjdCwga2V5LCB2YWx1ZSk7XG4gIGZvciAoY29uc3QgcmVzb2x2ZXIgb2YgcmVzb2x2ZXJzKSB7XG4gICAgcmVzb2x2ZXIucmVzb2x2ZShjb250ZXh0KTtcbiAgICBpZiAoY29udGV4dC5yZXBsYWNlZCkge1xuICAgICAgLy8gc3RvcCB3aGVuIHRoZSBmaXJzdCByZXNvbHZlciByZXBsYWNlcyB0aGUgdmFsdWUuXG4gICAgICByZXR1cm4gcmVzb2x2ZShrZXksIGNvbnRleHQucmVwbGFjZWRWYWx1ZSwgYXBpT2JqZWN0KTtcbiAgICB9XG4gIH1cblxuICAvLyBhcnJheSAtIHJlc29sdmUgZWFjaCBlbGVtZW50XG4gIGlmIChBcnJheS5pc0FycmF5KHZhbHVlKSkge1xuICAgIHJldHVybiB2YWx1ZS5tYXAoKHgsIGkpID0+IHJlc29sdmUoWy4uLmtleSwgYCR7aX1gXSwgeCwgYXBpT2JqZWN0KSk7XG4gIH1cblxuICAvLyBkaWN0aW9ucmFyeSAtIHJlc29sdmUgbGVhZnNcbiAgaWYgKHZhbHVlLmNvbnN0cnVjdG9yID09IE9iamVjdCkge1xuICAgIGNvbnN0IHJlc3VsdDogYW55ID0ge307XG4gICAgZm9yIChjb25zdCBbaywgdl0gb2YgT2JqZWN0LmVudHJpZXModmFsdWUpKSB7XG4gICAgICByZXN1bHRba10gPSByZXNvbHZlKFsuLi5rZXksIGtdLCB2LCBhcGlPYmplY3QpO1xuICAgIH1cbiAgICByZXR1cm4gcmVzdWx0O1xuICB9XG5cbiAgcmV0dXJuIHZhbHVlO1xuXG59XG4iXX0=