apiVersion: apps/v1
kind: Deployment
metadata:
  name: server
  labels:
    app: "server"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: "server"
  template:
    metadata:
      labels:
        app: "server"
    spec:
      containers:
        - name: server
          ports:
            - containerPort: 8080
          image: registry.cn-hangzhou.aliyuncs.com/lbemi/crmdb-server:v0.1
          imagePullPolicy: Always
      imagePullSecrets:
        - name: aliyun

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: web
  labels:
    app: "web"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: "web"
  template:
    metadata:
      labels:
        app: "web"
    spec:
      containers:
        - name: server
          ports:
            - containerPort: 80
          image: registry.cn-hangzhou.aliyuncs.com/lbemi/crmdb-web:v0.1
          imagePullPolicy: Always
      imagePullSecrets:
        - name: aliyun
---
apiVersion: v1
kind: Service
metadata:
  name: web-svc
  labels:
    app: web
spec:
  selector:
    app: web
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: web
  type: LoadBalancer
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: web
  annotations:
    ingress.kubernetes.io/ssl-redirect: "false"
spec:
  rules:
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: web-svc
                port:
                  number: 80