@token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE2NjY4NDM1NTYsImp0aSI6IjE1NzQzNDAzNDY2MzkyOTAzNjgiLCJpc3MiOiJhcHAiLCJuYmYiOjE2NjQyNTE1NTZ9.PS_-5i4zumgG1L7LIsCKhYgXovTKMBRp5vcR25xdPa8

### 登录
POST http://127.0.0.1:8080/login
Content-Type: application/json

{
  "user_name": "admin",
  "password": "admin",
  "mobile": "13338120030",
  "captcha": "14722",
  "captcha_id": "yBRooA83JKBFs9akf7kJ"
}
### 登出
GET http://127.0.0.1:8080/api/v1beat/user/logout
Authorization:  {{token}}

### 获取验证码
GET http://127.0.0.1:8080/captcha

### 注册
POST  http://127.0.0.1:8080/api/v1beat/user/register
Content-Type: application/json
Authorization:  {{token}}

{
  "user_name": "admin2",
  "password": "admin",
  "mobile": "13338120030",
  "email": "admin@admin.com"
}

###
GET http://127.0.0.1:8080/api/v1beat/user/ping
Content-Type: application/json
Authorization:  {{ token }}

###
GET http://127.0.0.1:8080/api/v1beat/user/info
Content-Type: application/json
Authorization:  {{ token }}
