# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.19
    - name: Login to Docker registry
      run: echo ${{ secrets.DOCKER_PASSWORD }} | docker login --username ${{ secrets.DOKCER_USER }} --password-stdin registry.cn-hangzhou.aliyuncs.com

    - name: Build
      run: cd ./server && make build
    - name: Push
      run: cd ./server && make push
    - name: Clean
      run: c ./server && make clean
 
